project:
  type: website
  output-dir: docs

website:
  title: "Sarayu Ramnath"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blog.qmd
        text: Blog
        
format:
  html:
    theme: cosmo
    css: styles.scss
    toc: true
    page-layout: full