project:
  type: website
  output-dir: docs
  resources:
    - Ramnath_CV.pdf
    - kolam_logo.png
    - styles.scss
    - posts/post_2/ramnath_nrs_infographic.pdf
    - posts/post_4/ramnath_policy_memo.pdf
    - posts/post_4/ramnath_public_comment_letter.pdf
execute:
  freeze: auto
website:
  title: "Sarayu Ramnath"
  navbar:
    logo: kolam_logo.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blog.qmd
        text: View my work
format:
  html:
    theme:
      - cosmo
      - styles.scss
    toc: true
    page-layout: full