project:
  type: website
  output-dir: docs
website:
  title: "Sarayu Ramnath"
  navbar:
    logo: kolam_logo.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blog.qmd
        text: Blog
      - href: cv.pdf
        text: CV
        
format:
  html:
    theme:
      - cosmo
      - styles.scss
    toc: true
    page-layout: full