<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sarayu Ramnath">
<meta name="dcterms.date" content="2025-12-01">
<meta name="description" content="Two computational modeling assignments from Climate Change Biology exploring habitat suitability and sea surface temperature projections under future emission scenarios.">

<title>Species Distribution &amp; Ocean Climate Modeling – Sarayu Ramnath</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-38af897ad0ac62e886f1f014e52bec95.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../kolam_logo.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Sarayu Ramnath</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blog.html"> 
<span class="menu-text">View my work</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
        
    </div>
<!-- main -->
<main class="content column-page" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Species Distribution &amp; Ocean Climate Modeling</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Species Distribution Modeling</div>
    <div class="quarto-category">Climate Science</div>
    <div class="quarto-category">Ocean Modeling</div>
    <div class="quarto-category">R</div>
  </div>
  </div>

<div>
  <div class="description">
    Two computational modeling assignments from Climate Change Biology exploring habitat suitability and sea surface temperature projections under future emission scenarios.
  </div>
</div>

<div class="quarto-title-meta-author column-page">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author"><a href="https://sarayu-26.github.io">Sarayu Ramnath</a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Bren School of Environmental Science &amp; Management, UCSB
          </p>
      </div>
  </div>

<div class="quarto-title-meta column-page">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 1, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="disclaimer">
  <p>⚠️ <strong>Note:</strong> These analyses were produced as coursework assignments for Climate Change Biology at UC Santa Barbara, Fall 2025. They are shared here as technical writing and modeling samples only.</p>
</div>
<p>Two modeling exercises exploring how climate change reshapes biological and oceanographic systems — one terrestrial, one marine. The first uses Maxent species distribution modeling to project habitat suitability for <em>Eschscholzia californica</em> (California poppy) under multiple emission scenarios. The second downloads and interprets CMIP6 ocean climate model output to examine projected sea surface temperature patterns.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true">Terrestrial SDM: California Poppy</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">Ocean SDM: Sea Surface Temperature</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="pub-brief-header">
  <p class="pub-source"><strong>Assignment:</strong> Species Distribution Modeling in Wallace<br>
  <strong>Species:</strong> <em>Eschscholzia californica</em> (California coastal poppy)<br>
  <strong>Tool:</strong> Wallace v2.0 / Maxent via ENMeval<br>
  <strong>Data:</strong> GBIF occurrence records (n=337 → 56 thinned); WorldClim v2.1 bioclimatic variables at 10 arc-minute resolution</p>
</div>
<section id="background" class="level3">
<h3 class="anchored" data-anchor-id="background">Background</h3>
<p><em>Eschscholzia californica</em>, the California state flower, is an iconic annual wildflower native to coastal regions and inland valleys of California. As a widespread native species, it provides early-season nectar resources for pollinators and contributes to California’s distinctive spring wildflower displays. While currently not threatened, understanding how climate change may alter its distribution is important for maintaining native biodiversity and ecosystem function.</p>
<p>Recent research has revealed significant genetic variation across the species’ range, with southern populations showing greater drought tolerance than northern populations. California is projected to experience substantial warming (2–5°C by 2100) and shifts in precipitation patterns, potentially restructuring suitable habitat for many native species. Species distribution modeling (SDM) offers a tool to anticipate these shifts and inform proactive conservation planning.</p>
</section>
<section id="methods" class="level3">
<h3 class="anchored" data-anchor-id="methods">Methods</h3>
<p>SDM was conducted using the Maxent algorithm as implemented in Wallace v2.0 via ENMeval. Occurrence data were obtained from GBIF and spatially thinned to a 20 km minimum distance to reduce sampling bias, yielding 56 training points. Six bioclimatic variables from WorldClim were selected to capture California’s Mediterranean climate:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>bio1</td>
<td>Annual mean temperature</td>
</tr>
<tr class="even">
<td>bio2</td>
<td>Mean diurnal temperature range</td>
</tr>
<tr class="odd">
<td>bio5</td>
<td>Maximum temperature of warmest month</td>
</tr>
<tr class="even">
<td>bio6</td>
<td>Minimum temperature of coldest month</td>
</tr>
<tr class="odd">
<td>bio12</td>
<td>Annual precipitation</td>
</tr>
<tr class="even">
<td>bio15</td>
<td>Precipitation seasonality</td>
</tr>
</tbody>
</table>
<p>The model was validated using spatial block cross-validation (k=4) and evaluated using cloglog output. Future climate projections for 2061–2080 were generated using the ACCESS-CM2 global circulation model under four Shared Socioeconomic Pathways (SSP 126, 245, 370, and 585).</p>
<div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Variable selection rationale:</strong> bio15 (precipitation seasonality) captures California’s wet winter/dry summer cycle; bio2 (diurnal temperature range) captures the coastal fog signature — small daily temperature swings that define the poppy’s coastal niche. Temperature and water availability together are the primary constraints on <em>E. californica</em> distribution.</p>
</div>
</div>
</div>
</section>
<section id="results" class="level3">
<h3 class="anchored" data-anchor-id="results">Results</h3>
<section id="baseline-habitat-suitability" class="level4">
<h4 class="anchored" data-anchor-id="baseline-habitat-suitability">Baseline Habitat Suitability</h4>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig1_baseline.png" class="img-fluid figure-img" style="width:40.0%"></p>
<figcaption><strong>Figure 1.</strong> Predicted habitat suitability for <em>Eschscholzia californica</em> under current climate conditions. Warmer colors indicate higher suitability. Model built using Maxent with six bioclimatic variables at 10 arc-minute resolution. Red circles represent thinned occurrence points (n=56) used for model training.</figcaption>
</figure>
</div>
<p>The baseline model successfully captured the current distribution of <em>E. californica</em>, predicting high habitat suitability along the California coast and in interior valleys where occurrence records are concentrated.</p>
</section>
<section id="future-projections-ssp-comparison-20612080" class="level4">
<h4 class="anchored" data-anchor-id="future-projections-ssp-comparison-20612080">Future Projections: SSP Comparison (2061–2080)</h4>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig2_ssp585.png" class="img-fluid figure-img" style="width:40.0%"></p>
<figcaption><strong>Figure 2.</strong> Projected habitat suitability under SSP 585 (high emissions, 2061–2080). Compared to baseline conditions, the model predicts substantial range expansion into the Central Valley, driven by warming temperatures.</figcaption>
</figure>
</div>
<p>The four SSP scenarios reveal a clear emissions-driven gradient in habitat expansion:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig3_ssp_grid.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption><strong>Figures 3–6.</strong> Habitat suitability projections under SSP 126 (low), SSP 245 (medium), SSP 370 (medium-high), and SSP 585 (high emissions), 2061–2080.</figcaption>
</figure>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 22%">
<col style="width: 23%">
<col style="width: 39%">
</colgroup>
<thead>
<tr class="header">
<th>Scenario</th>
<th>Emission Level</th>
<th>Habitat Change</th>
<th>Central Valley Suitability</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>SSP 126</td>
<td>Low</td>
<td>Minimal</td>
<td>Low</td>
</tr>
<tr class="even">
<td>SSP 245</td>
<td>Medium</td>
<td>Moderate expansion</td>
<td>Medium</td>
</tr>
<tr class="odd">
<td>SSP 370</td>
<td>Medium-High</td>
<td>Substantial expansion</td>
<td>High</td>
</tr>
<tr class="even">
<td>SSP 585</td>
<td>High</td>
<td>Maximum expansion</td>
<td>Very High</td>
</tr>
</tbody>
</table>
<p>Under SSP 126, suitable habitat remained largely like current conditions. As emission scenarios increased in severity, predicted suitable habitat expanded progressively northward and inland. Coastal suitable habitat remained stable across all scenarios — the primary differences occurred in interior areas. <strong>This pattern suggests <em>E. californica</em> is currently temperature-limited rather than water-limited;</strong> warmer temperatures appear to open previously unsuitable cooler interior regions.</p>
</section>
</section>
<section id="variable-choice-uncertainty" class="level3">
<h3 class="anchored" data-anchor-id="variable-choice-uncertainty">Variable Choice &amp; Uncertainty</h3>
<p>Different variables tell different stories. The model does not consider extreme drought events, winter chill hours, or fog data — all critical for coastal species. Temperature variables often correlate with each other, creating interpretation challenges when the model weights one variable heavily over a combination.</p>
<p>Scale also matters. At 10 arc-minute resolution (~20 km pixels), the model cannot capture microclimatic refugia such as fog-influenced coastal zones or north-facing slopes. The poppy is precipitation-limited, and climate models show less agreement on precipitation than temperature, contributing additional uncertainty. Using an alternative GCM would help explore this sensitivity.</p>
<div class="callout callout-style-simple callout-important no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>On eco-physical variables:</strong> Including soil type, elevation, and vegetation community data would improve realism — <em>E. californica</em> prefers loamy, well-drained coastal soils and depends on specific pH and drainage conditions. However, future projections of these static variables are largely unavailable or poorly constrained. Adding static eco-physical variables assumes those features won’t change, which contradicts the purpose of a climate projection. Dynamic variables like vegetation type would need their own future projections before being meaningfully incorporated — which is probably why most SDMs rely primarily on climate variables despite the limitations.</p>
</div>
</div>
</div>
</section>
<section id="management-recommendations" class="level3">
<h3 class="anchored" data-anchor-id="management-recommendations">Management Recommendations</h3>
<p><strong>1. Prioritize genetic integrity in restoration</strong> Southern populations exhibit greater drought tolerance, but hybridizing seed sources across regions could disrupt locally adapted coastal genotypes suited to fog-influenced environments. Restoration efforts should prioritize regionally sourced seed and develop regional seed banks that capture within-region variation without compromising genetic identity across ecozones.</p>
<p><strong>2. Integrate climate projections into habitat planning</strong> Use SDM outputs to guide restoration toward areas projected to remain or become suitable — particularly in the Central Valley and northern California under moderate to high emission scenarios. Avoid high investment in restoration in areas projected to lose suitability under high-emission scenarios. Focus on dynamic corridors that facilitate range shifts.</p>
<p><strong>3. Refine future models with non-climate variables</strong> Future SDMs should incorporate soil characteristics, vegetation community composition, and land use change data to constrain habitat predictions. Collaboration with land managers and soil ecologists could help identify barriers to natural recolonization in newly suitable areas.</p>
</section>
<section id="references" class="level3">
<h3 class="anchored" data-anchor-id="references">References</h3>
<p>Harrison, S., Franklin, J., Hernandez, R. R., Ikegami, M., Safford, H. D., &amp; Thorne, J. H. (2024). Climate change and California’s terrestrial biodiversity. <em>PNAS</em>, <em>121</em>(32), e2310074121. https://doi.org/10.1073/pnas.2310074121</p>
<p>Ryan, E. M., &amp; Cleland, E. E. (2021). Clinal variation in phenological traits and fitness responses to drought across the native range of California poppy. <em>Climate Change Ecology</em>, <em>2</em>, 100021. https://doi.org/10.1016/j.ecochg.2021.100021</p>
<p>Smither-Kopperl, M. L. (2018). <em>Plant guide for California poppy (Eschscholzia californica)</em>. USDA–NRCS Plant Materials Center.</p>
<hr>
</section>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="pub-brief-header">
  <p class="pub-source"><strong>Assignment:</strong> Ocean Model Download &amp; Plot<br>
  <strong>Model:</strong> GFDL-ESM4 (CMIP6 ScenarioMIP)<br>
  <strong>Ensemble member:</strong> r1i1p1f1 &nbsp;|&nbsp; <strong>Scenario:</strong> SSP5-8.5<br>
  <strong>Variable:</strong> Sea surface temperature (tos, °C) &nbsp;|&nbsp; <strong>Resolution:</strong> 1° × 1°</p>
</div>
<section id="background-1" class="level3">
<h3 class="anchored" data-anchor-id="background-1">Background</h3>
<p>Sea surface temperature (SST) reflects the thermal state of the upper ocean and directly impacts marine species’ physiology, metabolism, and survival. It is one of the most consequential variables in climate biology — warming SST drives thermal stress, prey-driven species redistribution, and food web disruption across ocean systems.</p>
<p>This exercise downloads and visualizes SST output from the GFDL-ESM4 climate model under the SSP5-8.5 high-emission scenario (CMIP6), examining projected ocean conditions for January 2015 as a baseline time step.</p>
</section>
<section id="model-metadata" class="level3">
<h3 class="anchored" data-anchor-id="model-metadata">Model Metadata</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Parameter</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Model</td>
<td>GFDL-ESM4</td>
</tr>
<tr class="even">
<td>Ensemble member</td>
<td>r1i1p1f1</td>
</tr>
<tr class="odd">
<td>Scenario</td>
<td>SSP5-8.5 (ssp585)</td>
</tr>
<tr class="even">
<td>Variable</td>
<td>tos (sea surface temperature)</td>
</tr>
<tr class="odd">
<td>Units</td>
<td>°C</td>
</tr>
<tr class="even">
<td>Native resolution</td>
<td>1° × 1° (lat/lon)</td>
</tr>
<tr class="odd">
<td>Global mean SST (first time step)</td>
<td>12.63°C</td>
</tr>
</tbody>
</table>
</section>
<section id="results-1" class="level3">
<h3 class="anchored" data-anchor-id="results-1">Results</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig_sst.png" class="img-fluid figure-img" style="width:60.0%"></p>
<figcaption><strong>Figure 1.</strong> Global sea surface temperature (SST, °C) projected for January 2015 under the SSP5-8.5 high-emission scenario using the GFDL-ESM4 climate model. Warm equatorial waters (red, 25–30°C) extend poleward to cold polar regions (blue, 0–5°C). Data: CMIP6 ScenarioMIP ensemble member r1i1p1f1.</figcaption>
</figure>
</div>
<p>The spatial pattern reflects characteristic ocean thermal structure: warm equatorial waters concentrated between 30°N and 30°S, with temperature declining sharply toward the poles. The global mean SST for this first time step is <strong>12.63°C</strong>.</p>
</section>
<section id="reflections" class="level3">
<h3 class="anchored" data-anchor-id="reflections">Reflections</h3>
<section id="what-does-sst-tell-us-about-ocean-conditions" class="level4">
<h4 class="anchored" data-anchor-id="what-does-sst-tell-us-about-ocean-conditions">What does SST tell us about ocean conditions?</h4>
<p>SST captures the thermal state of the upper ocean layer and directly governs marine species’ metabolic rates, growth, reproductive timing, and geographic ranges. It is one of the most widely used variables in ocean climate science precisely because it is measurable from both satellite and in situ platforms, and it integrates signals from atmospheric forcing, ocean circulation, and heat exchange.</p>
<p>However, SST alone has limitations. It only captures surface-level change. Mesopelagic temperatures (200–1000 m depth) matter because deeper waters can retain heat even after surface cooling, masking subsurface warming and potentially skewing assessments of ocean heat content and ecosystem recovery under future climate scenarios.</p>
</section>
<section id="conservation-relevance-sst-in-species-distribution-models" class="level4">
<h4 class="anchored" data-anchor-id="conservation-relevance-sst-in-species-distribution-models">Conservation relevance: SST in species distribution models</h4>
<p>SST can be incorporated directly into SDMs to predict where thermal conditions are suitable for a species to survive and reproduce. Temperature strongly influences physiology — metabolic rates, growth, and distribution limits all respond to thermal gradients. Incorporating SST identifies current and future habitat ranges under climate change, signals potential range shifts and habitat loss, and can reveal the emergence of newly suitable areas in previously cold regions.</p>
<p>For marine species with narrow thermal tolerances — coral reef systems, cold-water fish, marine mammals — SST projections under different SSPs can drive scenario planning for protected area design and fisheries management.</p>
</section>
<section id="temporal-insight-using-projections-to-guide-decisions-today" class="level4">
<h4 class="anchored" data-anchor-id="temporal-insight-using-projections-to-guide-decisions-today">Temporal insight: using projections to guide decisions today</h4>
<p>The downloaded file covers 2015–2034, though this figure displays only the January 2015 layer as a baseline. While a single time step doesn’t show temporal trends, comparing it against later decades in the dataset would reveal how SST is projected to shift over the coming two decades under SSP5-8.5.</p>
<p>Studying these projections across future time steps helps conservation planners anticipate habitat shifts and design adaptive strategies before thermal thresholds become critical — before bleaching events become chronic, before species ranges contract past recovery thresholds, before fisheries management frameworks become obsolete.</p>
<hr>
</section>
</section>
</div>
</div>
</div>
<style>
.pub-brief-header {
  background-color: rgba(32, 63, 81, 0.08);
  border-left: 4px solid #602013;
  padding: 1em 1.2em;
  margin-bottom: 1.5em;
  border-radius: 0 4px 4px 0;
}

.pub-source {
  margin: 0;
  font-size: 0.95em;
  color: #573F22;
  line-height: 1.8;
}

blockquote {
  border-left: 4px solid #C8C081;
  padding-left: 1em;
  color: #573F22;
  font-style: italic;
}

.disclaimer {
  background-color: rgba(200, 192, 129, 0.2);
  border-left: 4px solid #C8C081;
  padding: 0.8em 1.2em;
  margin-bottom: 1.5em;
  font-size: 0.85em;
  color: #573F22;
  border-radius: 0 4px 4px 0;
}

table {
  width: 100%;
  border-collapse: collapse;
  margin: 1.5em 0;
}

th {
  background-color: rgba(32, 63, 81, 0.15);
  color: #203F51;
  padding: 0.6em 1em;
  text-align: left;
}

td {
  padding: 0.5em 1em;
  border-bottom: 1px solid rgba(148, 136, 130, 0.3);
}
</style>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>